dist: bionic
language: csharp
dotnet: "3.1"
mono: none

env:
  global:
    - PATH="$PATH:$HOME/.dotnet/tools"

install:
  - dotnet tool restore -g paket

script:
 - paket install
 - dotnet restore
 - dotnet build
 - dotnet test
