name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        autofac: [ 'lowestSupported', '6.0.0' ]
    env:
      AutofacVersion: ${{matrix.autofac}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build
